# Generated by Django 5.1.6 on 2025-07-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='memberID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
