# Generated by Django 5.1.6 on 2025-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userebookletselection',
            name='view_option',
            field=models.CharField(choices=[('full', 'Full Access'), ('preview', 'Preview Only'), ('none', 'No Access')], default='none', max_length=20),
        ),
        migrations.RemoveField(
            model_name='userebookletselection',
            name='ebooklet',
        ),
        migrations.AddField(
            model_name='userebookletselection',
            name='ebooklet',
            field=models.ManyToManyField(to='core.ebooklet'),
        ),
    ]
