# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userebookletselection_view_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooklet',
            name='static_pdf_filename',
            field=models.CharField(blank=True, help_text="Filename of the static PDF file (e.g., 'B1_Boys.pdf')", max_length=255, null=True),
        ),
    ]
