# Generated by Django 4.2.9 on 2025-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='memberID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(blank=True, help_text='Date of Birth in DD-MM-YYYY format', max_length=10, null=True),
        ),
    ]
