# Generated by Django 4.2.9 on 2025-08-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_customuser_memberid_customuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
    ]
