# Generated by Django 4.2.9 on 2025-08-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(blank=True, help_text='Date of Birth in DD-MM-YYYY format', max_length=10, null=True),
        ),
    ]
